redis.host=localhost
redis.port=6379
redis.database=9
redis.password=

rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.username=guest
rabbitmq.password=guest
rabbitmq.virtualHost=/

controller.tickMillis=500
controller.maxCars=400
navigator.workerCount=8
